Repository richecr/CamaraDosDeputados, pull requests merged in 2020-10, with the labels that each got.

#67 Adicionar Proptypes
  package.json
  src/components/DeputadoCard/index.js
  src/components/Despesas/index.js
  src/components/PartidoCard/index.js
  src/components/Search/index.js
  src/components/paginacao/index.js
  src/helpers.js
  src/pages/DeputadoInfo/index.js
  src/pages/PartidoInfo/index.js
Labels: hacktoberfest-accepted

#70 Refatoração das extensões do arquivo, padronização e estrutura scss
  src/App.js
  src/components/DeputadoCard/index.js
  src/components/DeputadoCard/styles.scss
  src/components/Despesas/index.js
  src/components/Despesas/styles.scss
  src/components/Loader/index.js
  src/components/Loader/styles.scss
  src/components/PartidoCard/index.js
  src/components/PartidoCard/styles.scss
  src/components/paginacao/index.js
  src/components/paginacao/styles.scss
  src/global.scss
  src/pages/DeputadoInfo/index.js
  src/pages/DeputadoInfo/styles.scss
  src/pages/PartidoInfo/index.js
  src/pages/PartidoInfo/stylePagePartido.css
  src/pages/PartidoInfo/styles.scss
Labels: hacktoberfest-accepted

#79 Update README
  CONTRIBUTING.md
  README.md
Labels: Design

#87 Tela de perfil de um Deputado
  src/components/Despesas/index.js
  src/components/Despesas/styles.scss
  src/components/Pagination/index.js
  src/pages/DeputadoInfo/index.js
  src/pages/DeputadoInfo/styles.scss
Labels: enhancement, hacktoberfest-accepted

#89 Adicionando a nova logo
  src/assets/logo.png
  src/assets/logo.svg
  src/components/Header/index.js
  src/components/Header/styles.scss
Labels: enhancement, hacktoberfest-accepted

#90 Implementado a tela Home(sem ranking)
  src/assets/homeIllustration01.svg
  src/assets/homeIllustration02.svg
  src/assets/homeIllustration03.svg
  src/pages/Home/index.js
  src/pages/Home/styles.scss
  src/routes.js
Labels: hacktoberfest, hacktoberfest-accepted
